### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by frohro** [pedronveloso/android-digital-frame#1]
Hi,
I am looking for an open source digital photo frame app to put my old android phones to use with.  Does this build?  Do you have build instructions?
Thanks,
Rob

**Comment by frohro** [comment]
I was able to build it now, so I'll close this, as the instructions are not needed now.  I noticed you are actively working on this.  It is a great way to recycle your old phone.  I played around with changing the zip to mine, and picking my photos.  It appears you are using the /forecast/daily which is a paid API and the JSON returned is different from the free only weather API, so thanks for including your key.  It appears you really want to display the weather at the time displayed, but because you are using the forecast instead, it is not giving you the correct weather for this time.  I have never programmed in Kotelin, but perplexity.ai helped me modify the app to work with the weather API if that is of any interest to you.  I'm looking forward to all your new changes.  Thanks for providing this for all of us!

**Comment by pedronveloso** [comment]
Hi! @frohro 

Sorry for not getting back to you sooner, I didn't see your first message and I didn't get a notification for open issues until just now when you mentioned me on your second one. The project is still in its early days, although I've been using this for myself for over a year, as you probably had guesses from all the hard coding of location, etc. To address one of your topics, I intend to keep on developing it - focusing on privacy and OSS, which is something I felt I needed. I'm glad to see someone else found the project, and got a say I'm surprised as well given I haven't done any posts or mentions about it anywhere 😅 . I'm curious how you found it. And I'm glad you were able to compile and get it working for yourself - I'm yet to make it dev friendly or publish it. Good callout on the API endpoint for the weather, you're correct I'm looking current weather display. The API endpoint I'm using its likely rate limited, I'm not actually paying for it. It's fine, just use it, this just means I have to make a note to self to replace that in the future. If you have any other comments or suggestions feel free to tag me so I won't miss it in the future. Cheers!

**Comment by frohro** [comment]
Thanks @pedronveloso!
I found it searching using Google or github.  I tried the available apps on Google Play, and they all had annoying things trying to get folks to pay for the app (sometimes more than the old phone I'm using) so this does not provide a good way to reuse old phones.  I don't know Kotelin, but I can hack things and am willing to learn and like this use for old phones.  It brings good memories and the clock, and weather is nice.  I see how the days until the event could be nice too, but I'm getting old enough that I enjoy every day I'm given.  :-)  Phones make nice digital photo frames.  Even out-of-focus photos look good.
Thanks!
Rob

**Comment by pedronveloso** [comment]
@frohro Agreed, phones and tablets typically have much better screens than most digital albums you buy at an electronics store. I'm glad you found the app useful! I just did a few updates that make the app much more usable for anyone without requiring code modifications - just get the latest sources and compile. I changed to the correct endpoint from openweather's API like you have pointed out, and added a bunch of sensible settings. I feel its getting closer to being something worth releasing onto the Play Store and equivalent open stores. If you have further feedback I highly appreciate it.

**Comment by frohro** [comment]
@pedronveloso Wow!  Thanks!  It is much better, indeed.  

There are some things I notice on my Pixel 1.
1)  The new preferences are great, but if you get the little keyboard and try to hit the blue check, it doesn't accept it and keep what you typed.  It does seem to work to hit the back arrow button though.
2)  It would be nice to not always have the "days until" on the display.  I guess I'm getting too old to wish my remaining days away.  :-)
3)  You could just get the latitude and longitude from the location of the phone.  Having an option to put the latitude and longitude in too is nice so you can set it up as a gift for a friend a ways away, and it will be set up correctly for them.
4) On my phone, the only way to get rid of the square, circle and back-arrow is to quit the app (using the back-arrow) and restart.  If I use the circle, they are still there.  These navigation buttons appear when I use the Settings.
5)  You could have a setting that has a time that the photo only appears without any text, and the time it has text.  Sometimes I like to see just the photo, and that happens now, but not long enough.
Well, that is enough suggestions to keep you busy for a good while.  I have to say that already for my purposes, this app is better than the options on Google Play, because they all nag you to pay, and the price of the best one (Fotoo) is like $19.95 or something to remove the nag.
Thanks again for all your hard work on this.
Rob

**Comment by pedronveloso** [comment]
This is great, that's some fast feedback! Btw do get the latest couple of commits I made today, I noticed I had made the weather API poll way too often due to a bug that is now fixed!

Some quick answers:

1. Sounds like a bug. I'll put that on the list.

2. I'm planning on having enable/disable states for most "plugins" in the future. For now, you can hide it by selecting a date in the past.

3. Aggred. I was building on the existing stuff I had developed already. Will improve that in time.

4. That's annoying. The other thing that I must add and that's somewhat related and equally important is making the app more resilient. Either register as a Screensaver (yeah Android has that, fairly hidden and unused feature), or figure out some other way to guarantee the app can reopen if for some reason it crashes. It's rare but it happens.

5. My current plan is to bring awareness of sunrise/sunset from the weather data, and use that to further improve the overall experience based on that data. I'll take your suggestion into account when I tackle that. In general, like to strike a good balance between simplicity and personalization. And to keep true with the goal of having people use this app as a way to recycle old devices, I believe it's key that the app should work well out of the box.
Tangencial to this, something I want to change is make the photo rotation be in sync with the HUD fade operations. I'm imagining that the HUD would fade out, then the background image changes, and then the HUD would fade in again. It feels less clunky than what happens today, where these 2 things happen at different times, and it gives the viewer more time to appreciate the background image which is sorta what you're hinting at as well.
